= Propojení s IFTTT

== Co je IFTTT?

*IFTTT* (*„If This, Then That“*, což v překladu znamená „když se stane tohle, tak (udělej) toto“) slouží k automatizaci vašeho Internetu.

Funguje tak, že umí přebírat informace z nějaké služby – e-mailu, sociální sítě, cloud úložiště a řady dalších online služeb. Na základě informací z této zdrojové služby (*trigger*) umí něco udělat a výsledek předat cílové službě (*action*). Celý tento předpis se nazývá *Applet*.

Jako zdrojovou službu lze použít i tzv. *Maker* službu, která dovoluje komunikovat s IFTTT skrze webový požadavek (POST). Touto službou můžeme předat *až 3 hodnoty*, které můžeme následně použít například pro předání cílové službě (*action*).

To se nám bude hodit pro odesílání informací o našem zařízení.

== Jak vytvořit Applet?
.	Abychom si mohli vytvořit vlastní applet, je nutné se zaregistrovat na *IFTTT.com*.  
.	Po přihlášení stačí kliknutím na vaše uživatelské jméno v pravém horním rohu otevřít menu a zvolit *„New Applet“*.
.	Otevře se vám jednoduchá stránka s textem „if *this* then that“. Zde vybereme nejdříve zdrojovou službu *„this“*, která bude spouštět Applet a předávat data.
.	Zobrazí se dlouhý seznam všech možných zdrojových služeb. Pro náš účel vybereme službu *„Maker“*.
.	Připojíme se do Maker služby a zvolíme možnost služby *„Receive a web request“*.
.	Vyplníme *jméno události* a zvolíme *„Create trigger“*. Tím se vrátíme na stránku s „if this then *that*“.
.	Tentokrát ale nastavíme cílovou službu *„that“* (*action*).
.	Opět se nám otevře seznam všech služeb, které lze použít jako cílovou službu. Najdeme si službu, které chceme předávat informace. Pro tuto ukázku vybereme *Gmail*.	Přihlásíme se přes náš Gmail účet a zvolíme možnost *„Send an email“*.
.	Vyplníme adresu příjemce, předmět a zprávu. Ať už do zprávy nebo předmětu můžeme přidat tzv. *ingredience*, což jsou informace získané ze zdrojové služby. (3 hodnoty, název události a čas, kdy nastala událost)
.	Vytvoříme akci tlačítkem *„Create action“* a uložíme náš hotový Applet.

== Jak posílat data přes Maker službu do IFTTT?

Při vytváření účtu Maker služby se nám vygeneroval unikátní klíč, který dovoluje komunikovat právě s naším IFTTT účtem.

Tento klíč nalezneme v informacích o Maker účtu.

K informacím o Maker účtu se dostaneme následujícím způsobem:

.	Vyhledáme službu *Maker* (Na horní liště IFTTT stránky klikneme na *„Search“*).
.	Na stránce o službě vybereme v pravém horním rohu nastavení (tlačítko *„Settings“*), tím se dostaneme na informace o Maker účtu.
.	Zde nás zajímá *URL*, které obsahuje hledaný klíč. 
.	Při otevření URL odkazu můžeme otevřít *podrobný návod*, jak se pracuje s Maker službou.


Podle návodu, který jsme právě našli, sestavíme adresu, kam budeme odesílat data. 
*Výsledná adresa* bude vypadat takto:

[source]
--
https://maker.ifttt.com/trigger/{event}/with/key/{key}

{event} - název události (krok 6 v návodu, jak vytvořit applet)
{key} – váš vygenerovaný klíč k Maker 
--
Data se přes tuto adresu odesílají pomocí metody *POST* ve formátu *JSON*.

[source, json]
'{"value1":"hodnota1","value2":"hodnota2","value3":"hodnota3"}'


Jak již bylo popsáno výše, lze posílat *maximálně 3 hodnoty*.

== Příklad použití

=== *ifttt-bigclown*

Jednoduchý příklad implementace a použití IFTTT Maker služby s BigClown.

odkaz ke stažení: https://github.com/ondrejzemanek/ifttt-bigclown[*ifttt-bigclown @ Github*].


Použití
^^^^^^^
. Nastavení konstant pro komunikaci s IFTTT *Maker službou* souboru.
[source, python]
MAKER_SERVICE_NAME = {jméno události}
MAKER_SERVICE_KEY = {Maker klíč}

. Definice *spodní/horní hranice* a *hystereze teploty* natavením konstant 
[source, python]
TEMPERATURE_TRESHOLD_HIGH = {horní hranice teploty}
TEMPERATURE_TRESHOLD_LOW = {spodní hranice teploty}
TEMPERATURE_ALARM_HYSTERESIS = {hystereze alarmu teploty}

. Spuštění
[source]
python3 ifttt-bigclown.py